name: Test zsh-uv-env plugin

on:
  push:
    branches: [ main, pr-3 ]
  pull_request:
    branches: [ main ]

jobs:
  test-bash:
    runs-on: ubuntu-latest
    name: Test with Bash
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Run find_venv function tests
      shell: bash
      run: ./test-find-venv.sh
    
    - name: Run full plugin tests
      shell: bash
      run: ./test.sh
      continue-on-error: true  # Allow this to fail as it tests zsh-specific features
    
    - name: Test with real uv projects
      shell: bash
      run: |
        # Test .venv project
        mkdir -p test-project-dotenv
        cd test-project-dotenv
        uv venv .venv
        source ../zsh-uv-env.plugin.zsh 2>/dev/null || true
        
        # Test that find_venv works
        if command -v find_venv >/dev/null 2>&1; then
          result=$(find_venv)
          expected="$(pwd)/.venv"
          if [[ "$result" == "$expected" ]]; then
            echo "✅ Real uv .venv project test passed"
          else
            echo "❌ Real uv .venv project test failed: expected '$expected', got '$result'"
            exit 1
          fi
        else
          echo "⚠️  find_venv function not available, skipping real project test"
        fi
        
        cd ..
        
        # Test venv project
        mkdir -p test-project-venv
        cd test-project-venv
        uv venv venv
        source ../zsh-uv-env.plugin.zsh 2>/dev/null || true
        
        # Test that find_venv works
        if command -v find_venv >/dev/null 2>&1; then
          result=$(find_venv)
          expected="$(pwd)/venv"
          if [[ "$result" == "$expected" ]]; then
            echo "✅ Real uv venv project test passed"
          else
            echo "❌ Real uv venv project test failed: expected '$expected', got '$result'"
            exit 1
          fi
        else
          echo "⚠️  find_venv function not available, skipping real project test"
        fi

  test-zsh:
    runs-on: ubuntu-latest
    name: Test with Zsh
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install zsh
      run: sudo apt-get update && sudo apt-get install -y zsh
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Run find_venv function tests
      shell: zsh {0}
      run: ./test-find-venv.sh
